# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bank_bankinginfo',
            },
        ),
    ]
