# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'bank_bank',
            },
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankinfo', to='bank.Bank')),
            ],
            options={
                'db_table': 'bank_bankinfo',
            },
        ),
    ]
