# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remit_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('online_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('withdraw_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('withdraw_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_present', models.CharField(blank=True, max_length=100, null=True)),
                ('remit_check', models.CharField(blank=True, max_length=100, null=True)),
                ('service_rate', models.IntegerField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'NORMAL'), (0, 'DANGEROUS')], default=1)),
                ('cdt_deposit_num', models.IntegerField(blank=True, null=True)),
                ('cdt_deposit_amount', models.IntegerField(blank=True, null=True)),
                ('cdt_deposit_max', models.IntegerField(blank=True, null=True)),
                ('cdt_withdraw_num', models.IntegerField(blank=True, null=True)),
                ('cdt_withdraw_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'level_level',
            },
        ),
    ]
