# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('com_remit_limit', models.CommaSeparatedIntegerField(max_length=255)),
                ('com_remit_derate', models.CommaSeparatedIntegerField(max_length=10)),
                ('online_pay_limit', models.CommaSeparatedIntegerField(max_length=255)),
                ('online_pay_derate', models.CommaSeparatedIntegerField(max_length=10)),
                ('withdraw_limit', models.CommaSeparatedIntegerField(max_length=255)),
                ('withdraw_fee', models.FloatField()),
                ('withdraw_fee_way', models.IntegerField()),
                ('reg_present', models.CommaSeparatedIntegerField(max_length=10)),
                ('remit_check_rate', models.CommaSeparatedIntegerField(max_length=10)),
                ('service_rate', models.IntegerField()),
                ('memo', models.TextField()),
                ('status', models.IntegerField()),
                ('cdt_deposit_num', models.IntegerField()),
                ('cdt_deposit_amount', models.IntegerField()),
                ('cdt_deposit_max', models.IntegerField()),
                ('cdt_withdraw_num', models.IntegerField()),
                ('cdt_withdraw_amount', models.IntegerField()),
            ],
        ),
    ]
