# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='function_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
