# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'Inactive'), ('1', 'Active')], default=0)),
                ('invest_least', models.IntegerField()),
                ('deposit_fee', models.IntegerField()),
                ('deposit_fee_max', models.IntegerField()),
                ('withdraw_fee', models.IntegerField()),
                ('withdraw_fee_max', models.IntegerField()),
            ],
            options={
                'db_table': 'settings_commissionsettings',
            },
        ),
        migrations.CreateModel(
            name='ReturnSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'Inactive'), ('1', 'Active')], default=0)),
            ],
            options={
                'db_table': 'settings_returnsettings',
            },
        ),
    ]
