# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gametype', '0001_initial'),
        ('provider', '0001_initial'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=0)),
                ('member_num', models.IntegerField()),
                ('discount_rate', models.FloatField()),
                ('return_rate', models.FloatField()),
            ],
            options={
                'db_table': 'configsettings_commissiongroup',
            },
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('commission_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissionrate_group', to='configsettings.CommissionGroup')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_commissionconfig', to='provider.Provider')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_commissionconfig', to='gametype.GameType')),
            ],
            options={
                'db_table': 'configsettings_commissionrate',
            },
        ),
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('invest_least', models.IntegerField()),
                ('deposit_fee', models.IntegerField()),
                ('deposit_fee_max', models.IntegerField()),
                ('withdraw_fee', models.IntegerField()),
                ('withdraw_fee_max', models.IntegerField()),
            ],
            options={
                'db_table': 'configsettings_commissionsettings',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('threshold', models.CommaSeparatedIntegerField(max_length=10)),
                ('rate', models.FloatField()),
                ('check_rate', models.FloatField()),
                ('limit', models.CharField(blank=True, max_length=50, null=True)),
                ('online_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_online_discount', to='level.Level')),
                ('remit_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_remit_discount', to='level.Level')),
            ],
            options={
                'db_table': 'configsettings_discount',
            },
        ),
        migrations.CreateModel(
            name='ReturnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=0)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('check_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configsettings_returngroup',
            },
        ),
        migrations.CreateModel(
            name='ReturnRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_returnconfig', to='provider.Provider')),
                ('return_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnconfig_group', to='configsettings.ReturnGroup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_returnconfig', to='gametype.GameType')),
            ],
            options={
                'db_table': 'configsettings_returnrate',
            },
        ),
        migrations.CreateModel(
            name='ReturnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'db_table': 'configsettings_returnsettings',
            },
        ),
        migrations.AddField(
            model_name='returngroup',
            name='return_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returngroup_settings', to='configsettings.ReturnSettings'),
        ),
        migrations.AddField(
            model_name='commissiongroup',
            name='commission_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commgroup_settings', to='configsettings.CommissionSettings'),
        ),
    ]
